.TH SENTENCELENGTH 1 "December 2024" "v1" "User Commands"

.SH NAME
SentenceLength - a string length checker made in Python

.SH SYNOPSIS
sentenceLength

.SH DESCRIPTION
sentenceLength is a simple string length checker made in Python. It can be useful in some cases like doing math, counting letters, etc.

.SH INSTALLATION
Clone the git repository

.B git clone https://github.com/AronasGITHUB/sentenceLength.git

.B cd sentenceLength

Run the Makefile

.B sudo make install

Done!

.SH FILES

.B /bin/sentenceLength /usr/bin/sentenceLength /usr/local/bin/sentenceLength
Main executable.

.B /usr/share/man/man1/sentenceLength.1
Man page.

.SH SEE ALSO

.B bc(1)

.SH AUTHOR

Written by Aronas.

.SH LICENSE

sentenceLength is licensed under the MIT license.

