#!/usr/bin/python

# --------------------------------------------------------
# |       sentenceLength - a string length checker       |
# --------------------------------------------------------
#
#
# ~~~~~~~~~~~~~~~~~~~~~ Information ~~~~~~~~~~~~~~~~~~~
# / Licensed under the MIT license                    \
# | Made in Python                                    |
# | Supported for all OSes with Python installed      |
# \ for contributing guidelines, see CONTRIBUTING.md  /
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
#  -----------------------------------------
# / Dont worry, *   *     *  *   *    *   * \
# \   *     *    *    be happy! *   *   *   /
#  -----------------------------------------

print("----- setenceLength -----")

while True:
    string = input("(sentence) > ")

    print(len(string))
